# Generated by Django 5.2.8 on 2025-11-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listas', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='obras',
            field=models.ManyToManyField(blank=True, related_name='listas', to='obras.obra'),
        ),
    ]
