# Generated by Django 5.2.8 on 2025-11-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='obras.obra'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('obra',)},
        ),
    ]
